name: Link checker

# Error "Resource not accessible by integration"
# In organization: settings > actions > workflow permissions:
# - grant Read and write permissions
# - Allow GitHub Actions to create and approve pull requests

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    types: [closed]
  schedule:
    - cron: '10 2 * * 3'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  externalLinkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --verbose --no-progress
            --exclude-path _site
            --exclude-path _freeze
            --exclude-path .git
            --exclude-path node_modules
            **/*.qmd
            **/*.md


      - name: Create or Update Link Checker Issue
        # if: github.event_name != 'pull_request' && steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          issue-number: 142
          title: "Report: broken links (external)"
          content-filepath: ./lychee/out.md
          labels: report, automated issue, help-needed

  internalLinkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.email "digital-work-labot@users.noreply.github.com"
          git config --global user.name "digital-work-labot"
          git config --global url.https://github.com/.insteadOf git://github.com/

      - name: Set branch name
        run: |
          echo "BRANCH_NAME=link-fix-$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Switch to branch
        run: git checkout -b ${{ env.BRANCH_NAME }}

      - name: Fix links
        run: python .github/workflows/link_fix.py

      - name: Check for broken links file
        run: |
          if [ -f ./broken_links.md ]; then
            echo "found=true" >> $GITHUB_ENV
          else
            echo "found=false" >> $GITHUB_ENV
          fi

      - name: Create Issue From File
        if: github.event_name != 'pull_request' && env.found == 'true'
        uses: peter-evans/create-issue-from-file@v5
        with:
          issue-number: 143
          title: "Report: broken links (internal)"
          content-filepath: ./broken_links.md
          labels: report, automated issue, help-needed

      - name: Determine if changes have been made
        id: changed
        run: |
          rm -f broken_links.md
          echo "has_changes=$(git status --porcelain | wc -l | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Commit changes if any
        if: steps.changed.outputs.has_changes != '0'
        run: |
          git commit -a -m 'Fix links'
          git push --set-upstream origin ${{ env.BRANCH_NAME }}

      - name: Delete branch if no changes
        if: steps.changed.outputs.has_changes == '0'
        run: |
          git checkout main && git branch -D ${{ env.BRANCH_NAME }}

      - name: Create pull request
        if: steps.changed.outputs.has_changes != '0'
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "${{ env.BRANCH_NAME }}"
          destination_branch: "main"
          pr_title: "Fix links"
          pr_body: |
            *Fixed links*
